# Generated by Django 4.2.16 on 2024-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cartitem_observations_alter_cartitem_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.AddField(
            model_name='table',
            name='guest_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('V', 'Vacant'), ('O', 'Occupied'), ('R', 'Reserved')], default='V', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
