# Generated by Django 4.2.16 on 2024-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_table_is_available_table_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=2),
        ),
    ]
