# Generated by Django 4.2.16 on 2024-11-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_orderitem_bill_delete_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='table',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.order'),
        ),
    ]
