# Generated by Django 4.2.16 on 2024-11-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='api.table')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.bill'),
        ),
    ]
