# Generated by Django 4.2.16 on 2024-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bill_orderitem_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time_period',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('B', 'Both')], default='B', max_length=1),
        ),
    ]
