# Generated by Django 4.2.16 on 2024-12-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_promotion_discountcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='discount_value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_dishes',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_date',
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dish')),
            ],
        ),
    ]
