# Generated by Django 4.2.16 on 2024-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_promotionitem_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
