# Generated by Django 4.2.16 on 2024-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_orderitem_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='document',
            field=models.CharField(choices=[('V', 'Void'), ('T', 'Ticket'), ('I', 'Invoice')], default='V', max_length=1),
        ),
    ]
