# Generated by Django 4.2.16 on 2024-12-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_bill_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promotion'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.dish'),
        ),
    ]
